{% set name = "mne-ari" %}
{% set version = "0.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 60f9976ccc974ed69dbff02dd69b95c6e0ead9fcb5ec0c2d86f9d0d2fcbcc529

build:
  noarch: python
  number: 1
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - mne-base >=0.20
    - numpy >=1.15.4
    - scipy >=1.1.0

test:
  imports:
    - mne_ari
    - mne_ari.ari
    - mne_ari.permutation
    - mne_ari.ari.parametric
    - mne_ari.ari.permutation

  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check

about:
  home: https://github.com/john-veillette/mne_ari
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: All-resolutions Inference for M/EEG in Python.

extra:
  recipe-maintainers:
    - john-veillette
    - hoechenberger
    - larsoner
